FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o worker ./cmd/worker/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates openssh-client

WORKDIR /root/

COPY --from=builder /app/worker .

CMD ["./worker"]
