-- Track incremental ONT discovery progress for UI polling.
ALTER TABLE olts ADD COLUMN IF NOT EXISTS discovery_phase VARCHAR(20) NOT NULL DEFAULT 'idle';
ALTER TABLE olts ADD COLUMN IF NOT EXISTS discovery_total INTEGER NOT NULL DEFAULT 0;
ALTER TABLE olts ADD COLUMN IF NOT EXISTS discovery_registered INTEGER NOT NULL DEFAULT 0;
ALTER TABLE olts ADD COLUMN IF NOT EXISTS discovery_polled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE olts ADD COLUMN IF NOT EXISTS discovery_error TEXT;
ALTER TABLE olts ADD COLUMN IF NOT EXISTS discovery_started_at TIMESTAMPTZ;
ALTER TABLE olts ADD COLUMN IF NOT EXISTS discovery_last_poll_at TIMESTAMPTZ;
