package models

import (
	"testing"

	"github.com/google/uuid"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

// TestAutoMigrateProvisioningTables verifies that the new provisioning tables
// are created by AutoMigrate with the expected columns.
func TestAutoMigrateProvisioningTables(t *testing.T) {
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	if err != nil {
		t.Fatalf("open: %v", err)
	}

	if err := AutoMigrate(db); err != nil {
		t.Fatalf("AutoMigrate: %v", err)
	}

	for _, name := range []string{"config_templates", "provisioning_jobs", "batch_jobs"} {
		var exists bool
		if err := db.Raw(`SELECT EXISTS(SELECT 1 FROM sqlite_master WHERE type='table' AND name=?)`, name).Scan(&exists).Error; err != nil {
			t.Fatalf("check table %s: %v", name, err)
		}
		if !exists {
			t.Errorf("table %s was not created", name)
		}
	}
}

// TestConfigTemplateUUIDGeneration ensures a template gets a UUID on insert.
func TestConfigTemplateUUIDGeneration(t *testing.T) {
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	if err := AutoMigrate(db); err != nil {
		t.Fatalf("AutoMigrate: %v", err)
	}

	tmpl := ConfigTemplate{
		Name:         "default-zte",
		Vendor:       VendorZTE,
		ConfigFields: []byte(`{"vlan":100}`),
	}
	if err := db.Create(&tmpl).Error; err != nil {
		t.Fatalf("create template: %v", err)
	}
	if tmpl.ID == uuid.Nil {
		t.Error("template ID should be generated by BeforeCreate")
	}
}

// TestProvisioningJobUUIDGeneration ensures a job gets a UUID on insert.
func TestProvisioningJobUUIDGeneration(t *testing.T) {
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	if err := AutoMigrate(db); err != nil {
		t.Fatalf("AutoMigrate: %v", err)
	}

	job := ProvisioningJob{
		ONTID:  uuid.New(),
		Status: ProvisioningStatusPending,
	}
	if err := db.Create(&job).Error; err != nil {
		t.Fatalf("create job: %v", err)
	}
	if job.ID == uuid.Nil {
		t.Error("job ID should be generated by BeforeCreate")
	}
}

// TestBatchJobUUIDGeneration ensures a batch job gets a UUID on insert.
func TestBatchJobUUIDGeneration(t *testing.T) {
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	if err := AutoMigrate(db); err != nil {
		t.Fatalf("AutoMigrate: %v", err)
	}

	job := BatchJob{
		TemplateID: uuid.New(),
		ONTIDs:     UUIDSlice{uuid.New()},
		Status:     BatchStatusPending,
	}
	if err := db.Create(&job).Error; err != nil {
		t.Fatalf("create batch job: %v", err)
	}
	if job.ID == uuid.Nil {
		t.Error("batch job ID should be generated by BeforeCreate")
	}
	if len(job.ONTIDs) != 1 {
		t.Errorf("expected 1 ONT ID, got %d", len(job.ONTIDs))
	}
}

// TestUniqueTemplateNameEnforced checks the unique name constraint is active.
func TestUniqueTemplateNameEnforced(t *testing.T) {
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	if err := AutoMigrate(db); err != nil {
		t.Fatalf("AutoMigrate: %v", err)
	}

	if err := db.Create(&ConfigTemplate{Name: "dup", Vendor: VendorZTE}).Error; err != nil {
		t.Fatalf("first insert: %v", err)
	}
	if err := db.Create(&ConfigTemplate{Name: "dup", Vendor: VendorHSGQ}).Error; err == nil {
		t.Error("duplicate template name should be rejected")
	}
}
