import type { ThemeConfig } from 'antd';

export const theme: ThemeConfig = {
  token: {
    colorPrimary: '#3ecf8e',
    colorSuccess: '#3ecf8e',
    colorWarning: '#f59e0b',
    colorError: '#f04438',
    colorInfo: '#3b82f6',
    colorTextBase: '#1a1a1a',
    colorBgBase: '#ffffff',
    borderRadius: 6,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    fontSize: 14,
    controlHeight: 36,
    lineHeight: 1.5,
  },
  components: {
    Layout: {
      headerBg: '#ffffff',
      headerHeight: 56,
      headerPadding: '0 20px',
      siderBg: '#1c1c1c',
      bodyBg: '#f9fafb',
    },
    Menu: {
      itemBg: 'transparent',
      itemSelectedBg: 'rgba(62, 207, 142, 0.1)',
      itemSelectedColor: '#3ecf8e',
      itemHoverBg: 'rgba(255, 255, 255, 0.05)',
      itemHoverColor: '#ffffff',
      itemColor: '#a0a0a0',
      itemActiveBg: 'rgba(62, 207, 142, 0.15)',
      iconSize: 16,
      itemHeight: 36,
      itemMarginBlock: 2,
      itemMarginInline: 8,
      itemBorderRadius: 6,
      itemPaddingInline: 12,
    },
    Card: {
      borderRadiusLG: 8,
      paddingLG: 24,
      boxShadowTertiary: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
    },
    Table: {
      headerBg: '#fafafa',
      headerColor: '#666666',
      rowHoverBg: '#f5f5f5',
      borderColor: '#e5e7eb',
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
      borderRadius: 6,
    },
    Button: {
      borderRadius: 6,
      controlHeight: 36,
      fontWeight: 500,
      primaryShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    },
    Input: {
      borderRadius: 6,
      controlHeight: 36,
    },
    Select: {
      borderRadius: 6,
      controlHeight: 36,
    },
  },
};
