import type { ThemeConfig } from "antd";

export const theme: ThemeConfig = {
  token: {
    colorPrimary: "#3ecf8e",
    colorSuccess: "#3ecf8e",
    colorWarning: "#f59e0b",
    colorError: "#ef4444",
    colorInfo: "#3b82f6",
    colorTextBase: "#ffffff",
    colorBgBase: "#0a0a0a",
    colorBgContainer: "#18181b",
    colorBorder: "#27272a",
    colorBorderSecondary: "#27272a",
    borderRadius: 8,
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    fontSize: 14,
    controlHeight: 36,
    lineHeight: 1.5,
  },
  components: {
    Table: {
      headerBg: "#18181b",
      headerColor: "#a1a1aa",
      rowHoverBg: "#27272a",
      borderColor: "#27272a",
      bodySortBg: "#18181b",
      headerSortActiveBg: "#27272a",
      headerSortHoverBg: "#27272a",
      cellPaddingBlock: 12,
      cellPaddingInline: 16,
      borderRadius: 8,
      colorBgContainer: "#18181b",
      colorText: "#e5e5e5",
      colorTextHeading: "#a1a1aa",
    },
    Button: {
      borderRadius: 8,
      controlHeight: 36,
      fontWeight: 500,
      primaryShadow: "0 1px 2px 0 rgba(0, 0, 0, 0.2)",
      defaultBg: "#27272a",
      defaultColor: "#e5e5e5",
      defaultBorderColor: "#3f3f46",
      defaultHoverBg: "#3f3f46",
      defaultHoverColor: "#ffffff",
      defaultHoverBorderColor: "#52525b",
    },
    Input: {
      borderRadius: 8,
      controlHeight: 36,
      colorBgContainer: "#18181b",
      colorBorder: "#27272a",
      colorText: "#e5e5e5",
      colorTextPlaceholder: "#71717a",
      hoverBorderColor: "#3ecf8e",
      activeBorderColor: "#3ecf8e",
    },
    Select: {
      borderRadius: 8,
      controlHeight: 36,
      colorBgContainer: "#18181b",
      colorBorder: "#27272a",
      colorText: "#e5e5e5",
      colorTextPlaceholder: "#71717a",
      optionSelectedBg: "#27272a",
      optionActiveBg: "#3f3f46",
    },
    Modal: {
      contentBg: "#18181b",
      headerBg: "#18181b",
      titleColor: "#ffffff",
      colorText: "#e5e5e5",
      borderRadiusLG: 12,
    },
    Form: {
      labelColor: "#a1a1aa",
      labelFontSize: 14,
    },
    Card: {
      colorBgContainer: "#18181b",
      colorBorderSecondary: "#27272a",
      borderRadiusLG: 8,
      paddingLG: 24,
    },
    Dropdown: {
      colorBgElevated: "#18181b",
      colorText: "#e5e5e5",
      controlItemBgHover: "#27272a",
      controlItemBgActive: "#3f3f46",
    },
    Menu: {
      darkItemBg: "#0a0a0a",
      darkItemColor: "#a1a1aa",
      darkItemHoverBg: "rgba(62, 207, 142, 0.1)",
      darkItemHoverColor: "#ffffff",
      darkItemSelectedBg: "rgba(62, 207, 142, 0.15)",
      darkItemSelectedColor: "#3ecf8e",
      darkSubMenuItemBg: "#0a0a0a",
      itemHeight: 40,
      itemBorderRadius: 8,
      itemMarginInline: 8,
    },
    Tag: {
      defaultBg: "#27272a",
      defaultColor: "#e5e5e5",
    },
    // This theme sets a dark colorBgBase without darkAlgorithm, so Ant Design
    // still derives an alert's tinted background the light way: pale pink for
    // an error, under text this theme has already turned near-white. The login
    // failure was unreadable. Stating the tints here fixes every Alert at once.
    Alert: {
      colorErrorBg: "rgba(239, 68, 68, 0.12)",
      colorErrorBorder: "rgba(239, 68, 68, 0.4)",
      colorWarningBg: "rgba(245, 158, 11, 0.12)",
      colorWarningBorder: "rgba(245, 158, 11, 0.4)",
      colorSuccessBg: "rgba(62, 207, 142, 0.12)",
      colorSuccessBorder: "rgba(62, 207, 142, 0.4)",
      colorInfoBg: "rgba(59, 130, 246, 0.12)",
      colorInfoBorder: "rgba(59, 130, 246, 0.4)",
      colorText: "#e5e5e5",
      colorTextHeading: "#ffffff",
    },
    Statistic: {
      contentFontSize: 24,
      titleFontSize: 14,
    },
  },
};
export * from "./colors";
